language: php

sudo: false

before_install:
    - composer self-update

install:
    - composer install --dev --prefer-source

matrix:
    include:
        - php: 5.3.3
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: hhvm
        - php: 5.6
          env: SYMFONY_VERSION="2.8.*@dev"
        - php: 5.6
          env: SYMFONY_VERSION="3.0.*@dev"
    fast_finish: true

before_script:
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update "symfony/symfony:${SYMFONY_VERSION}"; fi;
